### ISSUE TITLE
AttributeError: module 'numpy.core' has no attribute 'numerictypes'

### ISSUE THREAD

**Issue by AureliusMarcusHu** [alvarobartt/investpy#432]
Hi Guys,

I'm very new in python and in I have installed investpy by pip. I get the notes all dependent packages are installed succesfully included investpy. I alsways get an error from numpy when I run the above command.

 File "C:\Program Files (x86)\Python39-32\lib\site-packages\numpy\__init__.py", line 200, in <module>
    core.numerictypes.typeDict,
AttributeError: module 'numpy.core' has no attribute 'numerictypes'

I have uninstalled and reinstalled the packages whitout succes. Always the same error.
Can someone help me please, what do I wrong ?

Thanks in advance.

**Comment by lone-wolf07** [comment]
I am facing the same issue. Please help!

**Comment by alvarobartt** [comment]
Hi @AureliusMarcusHu and @lone-wolf07 :hugs:

Thanks for reporting this issue! Are you both using Python 3.9? Which OS? And, finally, can you check which `numpy` version do you have installed?

Once you provide me that information I'll solve this ASAP :+1:

**Comment by alvarobartt** [comment]
Besides that, can you try to re-install `numpy` as it follows ``pip install numpy -U`

**Comment by nathan3leaf** [comment]
I'm assuming this is still in the broken phase?

**Comment by alvarobartt** [comment]
Hi @nathan3leaf, can you provide me more details? I think this is not happening anymore, just that the issue was not closed back in the day.

Is this function the one that is failing?

```python
information = investpy.get_stock_information(stock='AAPL', country='United States', as_json=True)
```

Thanks! :hugs:

**Comment by vmendezs** [comment]
Hey guys, I was having the same problem but then I made the next changes and it works for me:
1. Check the version of numpy and tensorflow with **pip show numpy** and **pip show tensorflow** (in my case I have 1.19.5 for numpy and 2.6.0 for tensorflow)
2. Also check the version of python, it is not necessary but just in case that you were working on python2.7 it won't work
3. Restart your machine, it helps the system to save the changes for the version of the packages
In case you don't know how to change the version of the packages, I changed them on the terminal with **python3 -m pip install numpy=1.19.5**

Hope it works for u, bye.

**Comment by alvarobartt** [comment]
Thanks for your suggestion @vmendezs, I'll try to re-run the unit tests with the latest version of `numpy` to see whether that works or not, and as soon as the unit tests are working I'll consider this issue closed. 👍🏻
